name: publish

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: gitTest
      run: |
        git --version
        ls
        git status
        git config --list
