name: publish

on:
  push:
    branches:
      - public
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: npm run build
    
    - name: publish
      run: |
        mv build docs
        git --version
